### ISSUE TITLE
Pow implementation for Integer and Rational

### ISSUE THREAD

**Issue by yannham** [mhogrefe/malachite#14]
Hello! I'm looking into malachite to use `Rational` as the underlying representation for numbers in the [Nickel configuration language](https://github.com/tweag/nickel).

Is there any reason (beside maybe not yet implemented - which is a valid reason!) why the `Pow` trait is not implemented for `Natural` and `Integer` exponents? That is:

```rust
impl Pow<Natural> for Natural { /* ... */ }
impl Pow<Natural> for Integer { /* ... */ }
impl Pow<Integer> for Rational { /* ... */ }
```

**Comment by mhogrefe** [comment]
Nickel looks cool! I hope you do end up using Malachite.

I haven't implemented `Pow<Natural>` or `Pow<Integer>` for any types because it doesn't seem very useful. If the exponent is too large to be represented by a `u64` then unless the base is -1, 0, or 1, the result can't be represented anyway.

I checked what some other libraries are doing. The `num` library [does](https://docs.rs/num/latest/num/struct.BigUint.html#impl-Pow%3CBigUint%3E) implement the analogous trait, but `rug` [doesn't](https://docs.rs/rug/latest/rug/struct.Integer.html) and [neither does](https://gmplib.org/manual/Integer-Exponentiation) GMP, which is the library that Malachite heavily borrows from.

**Comment by yannham** [comment]
Ah :man_facepalming: I just thought well those are exact operations, and the types match, so there should be such functions. Without thinking for one second that the result would be absolutely astronomic :sweat_smile: 

Thanks for the clarification :+1:
