### ISSUE TITLE
mod_pow not performing modulo when exponent is Natural::ONE

### ISSUE THREAD

**Issue by kikawet** [mhogrefe/malachite#24]
Where is broke?:

https://github.com/mhogrefe/malachite/blob/468b31a3d56887142f05ff0533ad56b4d3a38942/malachite-nz/src/natural/arithmetic/mod_pow.rs#L696

This should pass, but so far just returns 4 instead
```rust
    assert_eq!(
        (&Natural::from(4u8)).mod_pow(&Natural::from(1u8), &Natural::from(2u8)),
        Natural::ZERO
    )
```

**Comment by mhogrefe** [comment]
As [the documentation](https://docs.rs/malachite-nz/latest/malachite_nz/natural/struct.Natural.html#impl-ModPow%3CNatural,+Natural%3E-for-Natural) says, the `mod_pow` function assumes that the input is already reduced mod m. Since 4 is not reduced mod 2, the output is unspecified. You can use "% 2" on your input to reduce it before passing it to `mod_pow`.

You're not the first person to ask about this. In the near future I'll have all of these functions panic when given non-reduced inputs. The performance impact will be negligible, and it'll reduce the chance of unexpected results.

**Comment by mhogrefe** [comment]
In 0.4.3, all modular arithmetic functions panic if their inputs are not reduced.

**Comment by mhogrefe** [comment]
Sorry, v0.4.3 had some wrong dependencies. Please use v0.4.4 instead.

**Comment by kikawet** [comment]
Thank you for the change and remembering this after so much time, after reading the new change:
https://github.com/mhogrefe/malachite/blame/0799cf38fff1e77f0bd99c897c0423c3ffdea7f3/malachite-nz/src/natural/arithmetic/mod_pow.rs#L765

I suggest to update the message to help the user for a way to solve the incident, from:
`assert!(self < m, "self must be reduced mod m, but {self} >= {m}");`
to:
`assert!(self < m, "self must be reduced mod m, but {self} >= {m}, use mod_op operator");`

Up to you tho, the effort you already made this far with the management of the issues, is more than enough for me.
