### ISSUE TITLE
v0.4.5 docs build failed

### ISSUE THREAD

**Issue by amamic1803** [mhogrefe/malachite#38]
docs.rs build of docs for new version failed. I tried reading the log, it seems that it couldn't find embed-doc-image dependency, I don't understand why because that crate is available at crates.io.

**Comment by mhogrefe** [comment]
Sorry for the late reply. I'm not sure what's going on here, and since it works locally I'm not sure how to test changes. I just released v0.4.6 and tried tweaking some configurations while I was releasing, but it didn't help. I'll continue trying to figure it out. In the meantime, please use the documentation of the individual crates, for example [here](https://docs.rs/malachite-nz/latest/malachite_nz/).

**Comment by mhogrefe** [comment]
I fixed this in 0.4.7 by adding an embed-doc-images dependency to the top-level crate. The memory-layout image for `Natural` fails to render (compare [here](https://docs.rs/malachite/latest/malachite/struct.Natural.html) and [here](https://docs.rs/malachite-nz/latest/malachite_nz/natural/struct.Natural.html)), but that's a relatively minor issue.

**Comment by amamic1803** [comment]
I agree, it is better to have docs without image than not have docs at all.
