### ISSUE TITLE
Provide a permissive open-source license

### ISSUE THREAD

**Issue by AndrewWestberg** [mhogrefe/malachite#52]
Because of the way LGPL makes a distinction between static and dynamic linking, it is problematic for Rust code that always uses static linking to a library. As such, anything using this library could be considered a derived work.  Would you be open to allowing this crate to be licensed under a more permissive license such as Apache 2.0?

**Comment by mhogrefe** [comment]
Hi Andrew. Malachite is largely derived from GMP, MPFR, and FLINT, which are themselves licensed using LGPL. I'm not a lawyer, but I don't believe I have any choice but to license Malachite under LGPL as well.

**Comment by stickman561** [comment]
It depends on whether Malachite is counted as a derivative work or not. If it is, you need to keep LGPL. If not it’s yours to license as you see fit.  If you copied code directly, copied the same structure or private optimizations, or linked the project to those libraries in some way then yes, this is a derivative work and bound to the LGPL. If you merely took inspiration and used the same algorithms as those libraries, you SHOULD be safe to make the change. Code can be licensed by the GPL, algorithms cannot since they’re considered an abstract concept. What algorithms can be is PATENTED. In which case if you’re using algorithms patented by GNU then that’s another matter altogether. Releasing the library under Apache 2.0 would be massive, but to do so safely you need to determine the scope of your code and how closely it mirrors those original libraries. Getting in touch with the GNU team if you can and asking permission also can’t hurt. Good luck!
